import type { Car } from "./types";

/**
 * Demo-voorraad (8 occasions, ~€8k–€11k segment) uit het Claude Design-prototype.
 * TODO go-live: vervangen door echte voorraad (Leroy/Max) of een feed-koppeling.
 * Houd de shape gelijk; de UI leest alleen via de InventorySource-abstractie.
 */
export const CARS: Car[] = [
  {
    id: "polo",
    merk: "Volkswagen",
    model: "Polo",
    variant: "1.0 TSI Comfortline",
    prijs: 9450,
    bouwjaar: 2018,
    km: 78000,
    brandstof: "Benzine",
    transmissie: "Handgeschakeld",
    pk: 95,
    kleur: "Reflexzilver",
    deuren: 5,
    apk: "06-2027",
    verbruik: "1 op 18,5",
    status: "Beschikbaar",
    highlights: ["Airco & cruise control", "Apple CarPlay", "Nieuwe APK bij aflevering"],
    quote:
      "Deze Polo zou ik zo aan mijn eigen dochter meegeven: zuinig, compleet en technisch helemaal in orde.",
  },
  {
    id: "astra",
    merk: "Opel",
    model: "Astra",
    variant: "1.4 Turbo Edition",
    prijs: 10250,
    bouwjaar: 2017,
    km: 96000,
    brandstof: "Benzine",
    transmissie: "Handgeschakeld",
    pk: 150,
    kleur: "Mineraalzwart",
    deuren: 5,
    apk: "09-2026",
    verbruik: "1 op 16,0",
    status: "Beschikbaar",
    highlights: ["Navigatie & camera", "Parkeersensoren", "Volledig onderhouden"],
    quote:
      "Ruim, vlot en verrassend compleet, en toch betaalbaar. Een Astra waar je elke dag plezier van hebt.",
  },
  {
    id: "fiesta",
    merk: "Ford",
    model: "Fiesta",
    variant: "1.0 EcoBoost Titanium",
    prijs: 9950,
    bouwjaar: 2019,
    km: 64000,
    brandstof: "Benzine",
    transmissie: "Handgeschakeld",
    pk: 100,
    kleur: "Magnetic grijs",
    deuren: 5,
    apk: "03-2027",
    verbruik: "1 op 19,0",
    status: "Nieuw binnen",
    highlights: ["Climate control", "Stoel- & stuurverwarming", "Lichtmetalen velgen"],
    quote:
      "Net binnen en meteen favoriet: lage kilometers, fris en klaar om nog jaren mee te gaan.",
  },
  {
    id: "clio",
    merk: "Renault",
    model: "Clio",
    variant: "TCe 90 Zen",
    prijs: 8900,
    bouwjaar: 2018,
    km: 71000,
    brandstof: "Benzine",
    transmissie: "Handgeschakeld",
    pk: 90,
    kleur: "Wit",
    deuren: 5,
    apk: "11-2026",
    verbruik: "1 op 18,0",
    status: "Beschikbaar",
    highlights: ["Zuinig & wendbaar", "Bluetooth", "Ideale starter"],
    quote:
      "De ideale eerste auto: overzichtelijk, zuinig en gewoon fijn om mee weg te rijden.",
  },
  {
    id: "yaris",
    merk: "Toyota",
    model: "Yaris",
    variant: "1.5 Hybrid Active",
    prijs: 11450,
    bouwjaar: 2017,
    km: 88000,
    brandstof: "Hybride",
    transmissie: "Automaat",
    pk: 100,
    kleur: "Tinzilver",
    deuren: 5,
    apk: "05-2027",
    verbruik: "1 op 25,0",
    status: "Gereserveerd",
    highlights: ["Hybride, zeer zuinig", "Automaat", "Toyota onderhoudshistorie"],
    quote:
      "Wil je echt voordelig rijden, dan is deze hybride Yaris met automaat een gouden greep.",
  },
  {
    id: "308",
    merk: "Peugeot",
    model: "308",
    variant: "1.2 PureTech Allure",
    prijs: 10750,
    bouwjaar: 2018,
    km: 84000,
    brandstof: "Benzine",
    transmissie: "Automaat",
    pk: 110,
    kleur: "Grijs",
    deuren: 5,
    apk: "07-2026",
    verbruik: "1 op 17,5",
    status: "Beschikbaar",
    highlights: ["Automaat", "Navigatie & panodak", "Comfortabel op snelweg"],
    quote:
      "Ontspannen op de snelweg en met automaat ook in de stad relaxed: deze 308 maakt het je makkelijk.",
  },
  {
    id: "golf",
    merk: "Volkswagen",
    model: "Golf",
    variant: "1.2 TSI Comfortline",
    prijs: 10950,
    bouwjaar: 2016,
    km: 112000,
    brandstof: "Benzine",
    transmissie: "Handgeschakeld",
    pk: 110,
    kleur: "Donkerblauw",
    deuren: 5,
    apk: "02-2027",
    verbruik: "1 op 17,0",
    status: "Beschikbaar",
    highlights: ["Ruime gezinsauto", "Adaptive cruise", "Trekhaak"],
    quote:
      "Ruimte zat, trekhaak erop en betrouwbaar: precies de gezinsauto waar je op kunt bouwen.",
  },
  {
    id: "picanto",
    merk: "Kia",
    model: "Picanto",
    variant: "1.0 ComfortPlus",
    prijs: 8450,
    bouwjaar: 2019,
    km: 52000,
    brandstof: "Benzine",
    transmissie: "Handgeschakeld",
    pk: 67,
    kleur: "Rood",
    deuren: 5,
    apk: "08-2027",
    verbruik: "1 op 19,5",
    status: "Nieuw binnen",
    highlights: ["Lage kilometerstand", "Resterende fabrieksgarantie", "Perfect voor in de stad"],
    quote:
      "Weinig kilometers, nog fabrieksgarantie en perfect voor in de stad. Deze Picanto is zo weg.",
  },
];
